import { BatchDetail } from '../interfaces/batchDetail';

export const BatchDetails: BatchDetail[] = [
  {
    id: 'gfbgtbrtvgtgrf',
    batchId: '1',
    Ref_ID: 'asdsa-56asd23121',
    PropertyFullStreetAddress: 'James Brown 12/5',
    PropertyCity: 'New York',
    PropertyState: 'Washington',
    PropertyZip: '2202',
    APN: '42.412',
    Client: '708',
    Loan_Type: '13',
    Referral_Date: '15.08.2020',
    U20_Actual_Date: '15.08.2020',
    Voluntary: '',
    Non_Voluntary: '',
    FIPS: '09007',
    State: 'CT',
    County: 'TOLLAND',
    Parcel: 'PORT M:128 B:0034',
    CurrentOwner: 'Tigran Jamkochyan',
    ParsedHouseNumber: '11',
    ParsedStreetPreDir: '',
    ParsedStreetName: 'MICHELE DR',
    ParsedStreetTypeSuffix: 'DR',
    ParsedStreetPostDir: '',
    ParsedUnitType: '',
    ParsedUnitNumber: '2424',
    STNDAddress: '11 MICHELE DR',
    STNDUnitType: 'Unit',
    STNDUnitNum: '2424',
    STNDCity: 'Portland',
    STNDState: 'CT',
    STNDZip: '06480',
    STNDZip4: '1014',
    LandUseDesc: 'Single Family Residential',
    YearBuilt: 2012,
    Block: '34',
    Lot: '4-01',
    Subdivision: 'GOVERNORS COMMON',
    BriefLegal: '',
    Zone: 'R25',
    LatestSale_RecordingDate: '20100927',
    LatestSale_Book: '777',
    LatestSale_Page: '76',
    LatestSale_DocNumber: '',
    LatestSale_DocType: 'Quit Claim Deed',
    LatestSale_Subdivision: '',
    LatestSale_BriefLegal: '',
    LatestSale_CondoRider: 'N',
    LatestSale_PUDRider: 'N',
    LatestLoan_RecordingDate: '20060726',
    LatestLoan_Book: '645',
    LatestLoan_Page: '187',
    LatestLoan_DocNumber: '88',
    LatestLoan_Subdivision: '',
    LatestLoan_CondoRider: 'N',
    LatestLoan_PUDRider: 'N',
    LatestLoan_Source: 'S',
    Match: 'A',
    Zip9HOAIndicator: 'N',
    HOA_Indicator: 'Medium',
    HOA_Flag: '',
    Comments: '',
    PropertyAddress: '11 MICHELE DR',
    City: 'Portland',
    ZipCode: '06480',
    ReportDate: '06.07.2020',
    NbrOfHOAs: 1,
    HOA_1_Name: '',
    HOA_1_Type: '',
    HOA_1_Contact_Type: '',
    HOA_1_Contact_Name: '',
    HOA_1_Address_Mailing: '',
    HOA_1_City: '',
    HOA_1_State: '',
    HOA_1_Zip_Code: '',
    HOA_1_Contact_Phone_Type: '',
    HOA_1_Contact_Phone: 123456,
    HOA_1_Contact_Email: '',
    HOA_Contact_Type_2: '',
    HOA_1_Management_Company_Name: '',
    HOA_1_Management_Company_Address: '',
    HOA_1_Mangement_Company_City: '',
    HOA_1_Management_Company_State: '',
    HOA_1_Management_Company_Zip_Code: '',
    HOA_1_Management_Company_Phone_Type: '',
    HOA_1_Management_Company_Phone: '',
    HOA_1_Management_Company_Email: '',
    HOA_2_Name: '',
    HOA_2_Type: '',
    HOA_2_Contact_Type: '',
    HOA_2_Contact_Name: '',
    HOA_2_Address_Mailing: '',
    HOA_2_City: '',
    HOA_2_State: '',
    HOA_2_Zip_Code: '',
    HOA_2_Contact_Phone_Type: '',
    HOA_2_Contact_Phone: '',
    HOA_2_Contact_Email: '',
    HOA_2_Management_Company_Name: '',
    HOA_2_Management_Company_Contact_Name: '',
    HOA_2_Management_Company_Address: '',
    HOA_2_Mangement_Company_City: '',
    HOA_2_Management_Company_State: '',
    HOA_2_Management_Company_Zip_Code: '',
    HOA_2_Management_Company_Phone_Type: '',
    HOA_2_Management_Company_Phone: '',
    HOA_2_Management_Company_Email: '',
    prop: {
      landUse: 'asd',
      standardSubdivison: 'asd',
      subdivision2: 'sad',
      overrideSubdivision: 'ad',
    },

    hoa: {
      hoas: [
        {
          isMaster: true,
          hasMaster: false,
          voluntary: 'qwe',
          lastVerified: new Date(),
          verifiedMethod: 'GET',
        },
      ],
    },
  }
];
